#!/usr/bin/env python3
"""
Regenerate backend/docs/api.md by inspecting the FastAPI router.

Usage:
    python backend/tools/regen_docs.py

Called automatically by PostToolUse hook when any .py file in backend/ is edited.
"""
import sys
from pathlib import Path

# Allow imports from backend root
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from fastapi import FastAPI
from fastapi.routing import APIRoute

DOCS_DIR = Path(__file__).resolve().parents[1] / "docs"
DOCS_DIR.mkdir(exist_ok=True)


def collect_routes() -> list[dict]:
    """Import the FastAPI app and collect all routes."""
    try:
        import importlib
        import os
        os.environ.setdefault("USE_POSTGRES", "false")
        # Minimal import — avoid side effects from lifespan
        from fastapi import FastAPI as _FastAPI
        # We'll parse routes by importing individual routers
        routes = []
        router_modules = [
            ("leads", "api.routes.leads"),
            ("tasks", "api.routes.tasks"),
            ("analytics", "api.routes.analytics"),
            ("communications", "api.routes.communications"),
            ("outreach", "api.routes.outreach"),
            ("system", "api.routes.system"),
            ("ingest", "api.routes.ingest"),
            ("enrichment", "api.routes.enrichment"),
            ("listings", "api.routes.listings"),
            ("evidence", "api.routes.evidence"),
            ("control", "api.routes.control"),
            ("funnels", "api.routes.funnels"),
            ("property_intel", "api.routes.property_intel"),
            ("docs", "api.routes.docs"),
        ]
        for tag, mod_path in router_modules:
            try:
                mod = importlib.import_module(mod_path)
                router = getattr(mod, "router", None)
                if router is None:
                    continue
                for route in router.routes:
                    if hasattr(route, "methods") and hasattr(route, "path"):
                        for method in sorted(route.methods or []):
                            routes.append({
                                "tag": tag,
                                "method": method,
                                "path": route.path,
                                "summary": getattr(route, "summary", None) or (route.endpoint.__doc__ or "").strip().split("\n")[0],
                            })
            except Exception as e:
                routes.append({"tag": tag, "method": "?", "path": f"(import error: {e})", "summary": ""})
        return routes
    except Exception as e:
        return [{"tag": "error", "method": "?", "path": str(e), "summary": ""}]


def render_api_md(routes: list[dict]) -> str:
    lines = [
        "# API Reference",
        "",
        "> This file is auto-regenerated by `backend/tools/regen_docs.py`.",
        "> Run `python backend/tools/regen_docs.py` to update after changing routes.",
        "",
        "## Base URL",
        "",
        "`http://localhost:8001/api`",
        "",
        "## Authentication",
        "",
        "All endpoints require `X-API-KEY` header. Default: `HILLS_SECURE_2026_CORE`",
        "",
    ]

    by_tag: dict[str, list[dict]] = {}
    for r in routes:
        by_tag.setdefault(r["tag"], []).append(r)

    for tag, tag_routes in by_tag.items():
        lines.append(f"## {tag.replace('_', ' ').title()}")
        lines.append("")
        lines.append("| Method | Path | Description |")
        lines.append("|---|---|---|")
        for r in tag_routes:
            desc = r["summary"] or "—"
            lines.append(f"| `{r['method']}` | `{r['path']}` | {desc} |")
        lines.append("")

    return "\n".join(lines)


def main():
    print("Regenerating backend/docs/api.md...")
    routes = collect_routes()
    content = render_api_md(routes)
    out_path = DOCS_DIR / "api.md"
    out_path.write_text(content, encoding="utf-8")
    print(f"Written {len(routes)} routes to {out_path}")


if __name__ == "__main__":
    main()
